In [1]:
import numpy as np
from numpy import random as rg

In [2]:
a = np.floor(10 * rg.random((2,2)))
a

array([[6., 7.],
       [3., 0.]])

In [3]:
b = np.floor(10 * rg.random((2,2)))
b

array([[6., 4.],
       [2., 2.]])

In [4]:
np.vstack((a,b))

array([[6., 7.],
       [3., 0.],
       [6., 4.],
       [2., 2.]])

In [5]:
np.hstack((a,b))

array([[6., 7., 6., 4.],
       [3., 0., 2., 2.]])

In [6]:
a = np.floor(10 * rg.random((2,12)))
a

array([[5., 9., 8., 8., 3., 0., 8., 2., 8., 5., 0., 2.],
       [0., 2., 6., 2., 1., 1., 4., 1., 1., 5., 8., 7.]])

In [7]:
np.hsplit(a,3)

[array([[5., 9., 8., 8.],
        [0., 2., 6., 2.]]),
 array([[3., 0., 8., 2.],
        [1., 1., 4., 1.]]),
 array([[8., 5., 0., 2.],
        [1., 5., 8., 7.]])]

In [8]:
np.hsplit(a,12)

[array([[5.],
        [0.]]),
 array([[9.],
        [2.]]),
 array([[8.],
        [6.]]),
 array([[8.],
        [2.]]),
 array([[3.],
        [1.]]),
 array([[0.],
        [1.]]),
 array([[8.],
        [4.]]),
 array([[2.],
        [1.]]),
 array([[8.],
        [1.]]),
 array([[5.],
        [5.]]),
 array([[0.],
        [8.]]),
 array([[2.],
        [7.]])]

In [9]:
np.vsplit(a,2)

[array([[5., 9., 8., 8., 3., 0., 8., 2., 8., 5., 0., 2.]]),
 array([[0., 2., 6., 2., 1., 1., 4., 1., 1., 5., 8., 7.]])]

In [10]:
b = a
a is b # this is same object, has a b names

True