In [1]:
import numpy as np

In [2]:
def f(x,y):
    return 10 * x + y

In [3]:
b = np.fromfunction(f,(5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.ravel()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a.reshape(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
a.T #Transposed

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
a.T.shape

(4, 3)

In [9]:
a.shape

(3, 4)

In [10]:
a.resize(2,6)
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
a.reshape(3,-1) # if -1 is given, other dimensions are automatically calculated

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])