In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)

In [3]:
a.sum(axis = 0)

array([12, 15, 18, 21])

In [4]:
a.sum(axis = 1)

array([ 6, 22, 38])

In [5]:
b = np.arange(3)
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [6]:
c = np.array([2., -1., 4.])
np.add(b, c)

array([2., 0., 6.])

In [7]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [8]:
a = np.arange(10)**4
a

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [9]:
a[2:5]

array([ 16,  81, 256])

In [10]:
a[:6:2]

array([  0,  16, 256])

In [11]:
a[::-1]

array([6561, 4096, 2401, 1296,  625,  256,   81,   16,    1,    0])

In [12]:
for i in a:
    print(i ** (1/3.))

0.0
1.0
2.5198420997897464
4.3267487109222245
6.3496042078727974
8.549879733383484
10.902723556992836
13.390518279406722
15.999999999999998
18.720754407467133
